version: '3'
services:

  bash:
    image: node:9.8.0-alpine
    working_dir: /code
    volumes:
      - .:/code
    command: "sh"
    environment:
      - PATH=/code/node_modules/.bin/:$PATH

  web:
    image: node:9.8.0-alpine
    ports:
      - "5000:5000"
    working_dir: "/code"
    volumes:
      - .:/code
    command: "./node_modules/.bin/serve -p 5000"

  watch:
    image: node:9.8.0-alpine
    working_dir: "/code"
    volumes:
      - .:/code
    # maybe put the .bin in the path
    command: "./node_modules/.bin/webpack --config webpack.development.js -w --mode development"
